name: Coverage

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake gcc g++ gcovr \
            protobuf-compiler libprotobuf-dev

      - name: Run coverage
        run: ./coverage.sh

      - name: Generate XML for Codecov
        run: |
          mkdir -p build/coverage
          gcovr -r . build \
            --filter 'src/.*' \
            --exclude 'test/.*' \
            --exclude 'generated/.*' \
            --xml-pretty > build/coverage/coverage.xml

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build/coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: build/coverage/coverage.xml
